---
- hosts: localhost
  user: ansible
  become: yes
  connection: ssh


  tasks:
    - name: Install httpd if os is redhat linux
      command: yum install httpd -y
      when: ansible_os_family == "RedHat"

    - name: Install apache2 if os is ubuntu
      command: apt get install apache2 -y
      when: ansible_os_family == "Ubuntu"
