---
- hosts: dev
  user: ansible
  become: yes
  connection: ssh

  tasks:
     - name: Installing multiple toosls using with_items
       action: yum name='{{item}}' state=present
       with_items: 
          - git
          - maven
 

       
